#!/bin/bash
# -*- coding: utf-8 -*-
#
#  akiu - Antergos Kernel Installer Utility
#  Copyright © 2017 Antergos
#
#  Based on code from mhwd-kernel from Manjaro
#
#  Aiku is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  Aiku is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  The following additional terms are in effect as per Section 7 of the license:
#
#  The preservation of all legal notices and author attributions in
#  the material or in the Appropriate Legal Notices displayed
#  by works containing it is required.
#
#  You should have received a copy of the GNU General Public License
#  along with Aiku; If not, see <http://www.gnu.org/licenses/>.

set -euo pipefail

KERNEL_NAMES=""
KERNEL_AUR_NAMES=""
KERNEL_NAMES_FILE="kernels.txt"
KERNEL_AUR_NAMES_FILE="kernels-aur.txt"
AUR_HELPERS="yaourt packer pacaur"

err() {
    printf "\e[31mError:\e[0m $1\n" 1>&2; exit 1
}

root_check() {
    [[ $EUID != 0 ]] && err "Please run as root."
}

data_files_check() {
    if [[ ! -f $KERNEL_NAMES_FILE ]] || [[ ! -f $KERNEL_AUR_NAMES_FILE ]]; then
        err "Missing data files!"
    fi
}

args_check() {
    [[ $1 -lt $2 || $1 -gt $3 ]] && err "Please use the right amount of arguments (use -h for help)."
}

usage() {
    echo "Usage: akiu [option] [kernel(s)]
        -h  --help               Show this help message
        -i  --install            Install new kernel(s)
        -l  --list               List all available kernels
        -li --list-installed     List installed kernels
        -r  --remove             Remove kernel(s)
        -a  --aur                Enable AUR kernels (disabled by default)"
}

load_kernel_names() {
    KERNEL_NAMES=$(grep -h -v ^# ${KERNEL_NAMES_FILE} | grep -v '^[[:blank:]]*$' | cut -f1 -d ' ' | grep -v \\-docs | grep -v \\-headers | tr '\n' ' ')
    if [[ "$AUR_ENABLED" == "y" ]]; then
      KERNEL_AUR_NAMES=$(grep -h -v ^# ${KERNEL_AUR_NAMES_FILE} | grep -v '^[[:blank:]]*$' | cut -f1 -d ' ' | grep -v \\-docs | grep -v \\-headers | tr '\n' ' ')
    fi
}

kernel_list() {
    printf "\e[32mCurrently running:\e[0m $(uname -r) (${current})\n"
    echo "The following kernels are installed in your system:"
    names=()
    for kname in ${KERNEL_NAMES}; do
        name=$(pacman -Qqs $kname | grep -w ^$kname$)
        [[ ! -z "$name" ]] && echo $name
    done
    if [[ "$AUR_ENABLED" == "y" ]]; then
        for kname in ${KERNEL_AUR_NAMES}; do
            name=$($AUR_HELPER -Qqs $kname | grep -w ^$kname$)
            [[ ! -z "$name" ]] && echo "$name (aur)"
        done
    fi
}

kernel_repo() {
    printf "\e[32mAvailable kernels:\e[0m\n"
    for kname in ${KERNEL_NAMES}; do
        pacman -Ssq $kname | grep -w ^$kname$
    done
    if [[ "$AUR_ENABLED" == "y" ]]; then
        for kname in ${KERNEL_AUR_NAMES}; do
            echo "$($AUR_HELPER -Ssq $kname | grep -w ^$kname$) (aur)"
        done
    fi
}

kernel_remove() {
    pkgremove=()

    for kernel in "$@"; do
        [[ -z "$kernel" ]] && err "Invalid argument (use -h for help)."
        [[ ${KERNEL_NAMES} != *"$kernel"* ]] && [[ ${KERNEL_AUR_NAMES} != *"$kernel"* ]] && err "Please enter a valid kernel name.\n$(kernel_list)"
        [[ $current_kernel_name = $kernel ]] && err "You can't remove your current kernel."
        [[ -z $(pacman -Qqs "^$1$") ]] && err "Kernel not installed.\n$(kernel_list)"

        for pkg in $(pacman -Qqs "$kernel"); do
            pkgremove+=("$pkg")
        done
    done

    echo "pacman -R \"${pkgremove[@]}\""
}

kernel_install() {
    pkginstall=()
    rmc=0

    for kernel in "$@"; do
        [[ $kernel = "rmc" ]] && rmc=1 && continue
        [[ $kernel != linux[0-9][0-9]?([0-9]) && $kernel != linux-rt-*manjaro && $kernel != "rmc" ]] && err "Invalid argument.\nPlease choose one of the $(kernel_repo)"
        [[ $current_kernel_name = $kernel ]] && err "You can't reinstall your current kernel. Please use 'pacman -Syu' instead to update."
        [[ -z $(pacman -Ssq "^$kernel$") ]] && err "Please make sure if the given kernel(s) exist(s).\n$(kernel_repo)"

        for pkg in $(pacman -Qqs "$current"); do
            pkg=${pkg//$current/$kernel}
            [[ -n $(pacman -Ssq "^$pkg$") ]] && pkginstall+=("$pkg")
        done
    done

    pacman -Syy

    outofdate="$(pacman -Qqu | tr '\n' ' ')"
    if [[ -n $outofdate ]]; then
        echo "The following packages are out of date, please update your system first: $outofdate" >&2
        read -p "Do you want to continue anyway? [y/N] " yesno
        [[ $yesno = [Yy]?([Ee][Ss]) ]] || exit 1
    fi

    pacman -S "${pkginstall[@]}"

    [[ $rmc = 1 && $? = 0 ]] && pacman -R $(pacman -Qqs $current)
    [[ $rmc = 1 && $? != 0 ]] && { echo ""; err "'rmc' aborted because the kernel failed to install or canceled on removal."; }
}

check_aur_helper() {
    AUR_HELPER=""
    for helper in $AUR_HELPERS; do
        if [[ "$(pacman -Qsq $helper)" != "" ]]; then
            AUR_HELPER=$helper
            return 0
        fi
    done
    err "You need to install one of these AUR helpers ($AUR_HELPERS)"
}

###############################################################################

IFS=. read -r major minor _ <<< "$(uname -r)"
current_kernel_name=$(uname -s)
current="$current_kernel_name $major.$minor"
#[[ $(uname -r) == *rt* ]] && [[ $current == $rt_base ]] && current=linux-rt-manjaro
#[[ $(uname -r) == *rt* ]] && [[ $current == $rt_lts_base ]] && current=linux-rt-lts-manjaro

check_aur_helper

AUR_ENABLED="n"
for param in $@; do
    if [[ "$param" == "--aur" ]] || [[ "$param" == "-a" ]]; then
        AUR_ENABLED="y"
        printf "(Using \e[32m$helper\e[0m AUR helper)\n"
    fi
done

data_files_check
load_kernel_names

while :; do
    case ${1:-"-h"} in
        -h|-\?|--help)          usage
                                exit 0 ;;
        -i|--install)           if [ "${2:-}" ]; then
                                    root_check
                                    shift
                                    echo "kernel_install $@"
                                    exit 0
                                else
                                    err "Invalid arguments (use -h for help)."
                                fi ;;
        -l|--list-all)          kernel_repo
                                exit 0 ;;
        -li|--list-installed)   kernel_list
                                exit 0 ;;
        -r|--removed)           if [ "${2:-}" ]; then
                                    root_check
                                    shift
                                    echo "kernel_remove $@"
                                    exit 0
                                else
                                    err "Invalid arguments (use -h for help)."
                                fi ;;
        --)                     shift
                                break ;;
        *)                      echo "Invalid argument '${1:-}'."
                                usage
                                exit 0 ;;
    esac
done
